# Autogen Installation


1. Create a venv
2. Create a requirements.txt
3. pip install autogen-agentchat, autogen-core autogen-ext

# First Autogen Agent


In [2]:
from autogen_agentchat.agents import AssistantAgent
from autogen_ext.models.openai import OpenAIChatCompletionClient

In [4]:
from dotenv import load_dotenv
import os

load_dotenv()

True

In [5]:
api_key= os.getenv("OPENAI_API_KEY")

# Connecting to the Model

In [6]:
model_client= OpenAIChatCompletionClient(model='gpt-4o', api_key=api_key)

In [9]:
my_first_agent= AssistantAgent(name='my_assistant', model_client=model_client)

In [10]:
my_first_agent

In [11]:
result= await my_first_agent.run(task='Tell me something about you?')

In [12]:
print(result)

messages=[TextMessage(id='136ab700-6f2c-4782-9e88-d726fca8d2f3', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 7, 6, 10, 21, 18, 251295, tzinfo=datetime.timezone.utc), content='Tell me something about you?', type='TextMessage'), TextMessage(id='d8f1874d-1af0-4566-94df-4bd0bb5291cb', source='my_assistant', models_usage=RequestUsage(prompt_tokens=42, completion_tokens=65), metadata={}, created_at=datetime.datetime(2025, 7, 6, 10, 21, 20, 268207, tzinfo=datetime.timezone.utc), content='I am an AI assistant designed to help with a variety of tasks, answer questions, and provide information based on the data I have been trained on up until October 2023. I can assist with a wide range of topics including science, technology, history, and more. Let me know how I can assist you today!', type='TextMessage')] stop_reason=None


messages=[TextMessage(id='136ab700-6f2c-4782-9e88-d726fca8d2f3', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 7, 6, 10, 21, 18, 251295, tzinfo=datetime.timezone.utc), content='Tell me something about you?', type='TextMessage'), TextMessage(id='d8f1874d-1af0-4566-94df-4bd0bb5291cb', source='my_assistant', models_usage=RequestUsage(prompt_tokens=42, completion_tokens=65), metadata={}, created_at=datetime.datetime(2025, 7, 6, 10, 21, 20, 268207, tzinfo=datetime.timezone.utc), content='I am an AI assistant designed to help with a variety of tasks, answer questions, and provide information based on the data I have been trained on up until October 2023. I can assist with a wide range of topics including science, technology, history, and more. Let me know how I can assist you today!', type='TextMessage')] stop_reason=None

In [13]:
result2 = await my_first_agent.run(task='What was my last question?')

In [14]:
result2

TaskResult(messages=[TextMessage(id='03c18107-8798-4250-adc0-498da29ea8ff', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 7, 6, 10, 21, 58, 594744, tzinfo=datetime.timezone.utc), content='What was my last question?', type='TextMessage'), TextMessage(id='b0fe01ef-d20b-4994-8e58-82e96c774ed2', source='my_assistant', models_usage=RequestUsage(prompt_tokens=122, completion_tokens=12), metadata={}, created_at=datetime.datetime(2025, 7, 6, 10, 21, 59, 521738, tzinfo=datetime.timezone.utc), content='Your last question was: "Tell me something about you?"', type='TextMessage')], stop_reason=None)

TaskResult(messages=[TextMessage(id='03c18107-8798-4250-adc0-498da29ea8ff', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 7, 6, 10, 21, 58, 594744, tzinfo=datetime.timezone.utc), content='What was my last question?', type='TextMessage'), TextMessage(id='b0fe01ef-d20b-4994-8e58-82e96c774ed2', source='my_assistant', models_usage=RequestUsage(prompt_tokens=122, completion_tokens=12), metadata={}, created_at=datetime.datetime(2025, 7, 6, 10, 21, 59, 521738, tzinfo=datetime.timezone.utc), content='Your last question was: "Tell me something about you?"', type='TextMessage')], stop_reason=None)